// Liste complète des 114 sourates du Coran avec nom arabe, nom phonétique, slug et traduction anglaise
// Copie ce contenu dans sourateSlugs.ts pour remplacer la liste actuelle
export const sourates = [
  { number: 1, slug: "al-faatiha", nom_phonetique: "Al-Faatiha", nom_arabe: "سورة الفاتحة", englishNameTranslation: "The Opening" },
  { number: 2, slug: "al-baqara", nom_phonetique: "Al-Baqara", nom_arabe: "سورة البقرة", englishNameTranslation: "The Cow" },
  { number: 3, slug: "al-imran", nom_phonetique: "Al-Imran", nom_arabe: "سورة آل عمران", englishNameTranslation: "The Family of Imran" },
  { number: 4, slug: "an-nisa", nom_phonetique: "An-Nisa", nom_arabe: "سورة النساء", englishNameTranslation: "The Women" },
  { number: 5, slug: "al-ma-idah", nom_phonetique: "Al-Ma'idah", nom_arabe: "سورة المائدة", englishNameTranslation: "The Table Spread" },
  { number: 6, slug: "al-an-am", nom_phonetique: "Al-An'am", nom_arabe: "سورة الأنعام", englishNameTranslation: "The Cattle" },
  { number: 7, slug: "al-a-raf", nom_phonetique: "Al-A'raf", nom_arabe: "سورة الأعراف", englishNameTranslation: "The Heights" },
  { number: 8, slug: "al-anfal", nom_phonetique: "Al-Anfal", nom_arabe: "سورة الأنفال", englishNameTranslation: "The Spoils of War" },
  { number: 9, slug: "at-tawbah", nom_phonetique: "At-Tawbah", nom_arabe: "سورة التوبة", englishNameTranslation: "The Repentance" },
  { number: 10, slug: "yunus", nom_phonetique: "Yunus", nom_arabe: "سورة يونس", englishNameTranslation: "Jonah" },
  { number: 11, slug: "hud", nom_phonetique: "Hud", nom_arabe: "سورة هود", englishNameTranslation: "Hud" },
  { number: 12, slug: "yusuf", nom_phonetique: "Yusuf", nom_arabe: "سورة يوسف", englishNameTranslation: "Joseph" },
  { number: 13, slug: "ar-ra-d", nom_phonetique: "Ar-Ra’d", nom_arabe: "سورة الرعد", englishNameTranslation: "The Thunder" },
  { number: 14, slug: "ibrahim", nom_phonetique: "Ibrahim", nom_arabe: "سورة إبراهيم", englishNameTranslation: "Abraham" },
  { number: 15, slug: "al-hijr", nom_phonetique: "Al-Hijr", nom_arabe: "سورة الحجر", englishNameTranslation: "The Rocky Tract" },
  { number: 16, slug: "an-nahl", nom_phonetique: "An-Nahl", nom_arabe: "سورة النحل", englishNameTranslation: "The Bee" },
  { number: 17, slug: "al-isra", nom_phonetique: "Al-Isra", nom_arabe: "سورة الإسراء", englishNameTranslation: "The Night Journey" },
  { number: 18, slug: "al-kahf", nom_phonetique: "Al-Kahf", nom_arabe: "سورة الكهف", englishNameTranslation: "The Cave" },
  { number: 19, slug: "maryam", nom_phonetique: "Maryam", nom_arabe: "سورة مريم", englishNameTranslation: "Mary" },
  { number: 20, slug: "taha", nom_phonetique: "Taha", nom_arabe: "سورة طه", englishNameTranslation: "Ta-Ha" },
  { number: 21, slug: "al-anbiya", nom_phonetique: "Al-Anbiya", nom_arabe: "سورة الأنبياء", englishNameTranslation: "The Prophets" },
  { number: 22, slug: "al-hajj", nom_phonetique: "Al-Hajj", nom_arabe: "سورة الحج", englishNameTranslation: "The Pilgrimage" },
  { number: 23, slug: "al-mu-minun", nom_phonetique: "Al-Mu’minun", nom_arabe: "سورة المؤمنون", englishNameTranslation: "The Believers" },
  { number: 24, slug: "an-nur", nom_phonetique: "An-Nur", nom_arabe: "سورة النور", englishNameTranslation: "The Light" },
  { number: 25, slug: "al-furqan", nom_phonetique: "Al-Furqan", nom_arabe: "سورة الفرقان", englishNameTranslation: "The Criterion" },
  { number: 26, slug: "ash-shu-ara", nom_phonetique: "Ash-Shu’ara", nom_arabe: "سورة الشعراء", englishNameTranslation: "The Poets" },
  { number: 27, slug: "an-naml", nom_phonetique: "An-Naml", nom_arabe: "سورة النمل", englishNameTranslation: "The Ant" },
  { number: 28, slug: "al-qasas", nom_phonetique: "Al-Qasas", nom_arabe: "سورة القصص", englishNameTranslation: "The Stories" },
  { number: 29, slug: "al-ankabut", nom_phonetique: "Al-Ankabut", nom_arabe: "سورة العنكبوت", englishNameTranslation: "The Spider" },
  { number: 30, slug: "ar-rum", nom_phonetique: "Ar-Rum", nom_arabe: "سورة الروم", englishNameTranslation: "The Romans" },
  { number: 31, slug: "luqman", nom_phonetique: "Luqman", nom_arabe: "سورة لقمان", englishNameTranslation: "Luqman" },
  { number: 32, slug: "as-sajda", nom_phonetique: "As-Sajda", nom_arabe: "سورة السجدة", englishNameTranslation: "The Prostration" },
  { number: 33, slug: "al-ahzab", nom_phonetique: "Al-Ahzab", nom_arabe: "سورة الأحزاب", englishNameTranslation: "The Confederates" },
  { number: 34, slug: "saba", nom_phonetique: "Saba", nom_arabe: "سورة سبإ", englishNameTranslation: "Sheba" },
  { number: 35, slug: "fatir", nom_phonetique: "Fatir", nom_arabe: "سورة فاطر", englishNameTranslation: "The Originator" },
  { number: 36, slug: "ya-sin", nom_phonetique: "Ya-Sin", nom_arabe: "سورة يس", englishNameTranslation: "Ya-Sin" },
  { number: 37, slug: "as-saffat", nom_phonetique: "As-Saffat", nom_arabe: "سورة الصافات", englishNameTranslation: "Those who set the Ranks" },
  { number: 38, slug: "sad", nom_phonetique: "Sad", nom_arabe: "سورة ص", englishNameTranslation: "The Letter Sad" },
  { number: 39, slug: "az-zumar", nom_phonetique: "Az-Zumar", nom_arabe: "سورة الزمر", englishNameTranslation: "The Groups" },
  { number: 40, slug: "ghafir", nom_phonetique: "Ghafir", nom_arabe: "سورة غافر", englishNameTranslation: "The Forgiver" },
  { number: 41, slug: "fussilat", nom_phonetique: "Fussilat", nom_arabe: "سورة فصلت", englishNameTranslation: "Explained in Detail" },
  { number: 42, slug: "ash-shura", nom_phonetique: "Ash-Shura", nom_arabe: "سورة الشورى", englishNameTranslation: "The Consultation" },
  { number: 43, slug: "az-zukhruf", nom_phonetique: "Az-Zukhruf", nom_arabe: "سورة الزخرف", englishNameTranslation: "The Gold Adornments" },
  { number: 44, slug: "ad-dukhan", nom_phonetique: "Ad-Dukhan", nom_arabe: "سورة الدخان", englishNameTranslation: "The Smoke" },
  { number: 45, slug: "al-jathiya", nom_phonetique: "Al-Jathiya", nom_arabe: "سورة الجاثية", englishNameTranslation: "The Crouching" },
  { number: 46, slug: "al-ahqaf", nom_phonetique: "Al-Ahqaf", nom_arabe: "سورة الأحقاف", englishNameTranslation: "The Wind-Curved Sandhills" },
  { number: 47, slug: "muhammad", nom_phonetique: "Muhammad", nom_arabe: "سورة محمد", englishNameTranslation: "Muhammad" },
  { number: 48, slug: "al-fath", nom_phonetique: "Al-Fath", nom_arabe: "سورة الفتح", englishNameTranslation: "The Victory" },
  { number: 49, slug: "al-hujurat", nom_phonetique: "Al-Hujurat", nom_arabe: "سورة الحجرات", englishNameTranslation: "The Rooms" },
  { number: 50, slug: "qaf", nom_phonetique: "Qaf", nom_arabe: "سورة ق", englishNameTranslation: "The Letter Qaf" },
  { number: 51, slug: "adh-dhariyat", nom_phonetique: "Adh-Dhariyat", nom_arabe: "سورة الذاريات", englishNameTranslation: "The Winnowing Winds" },
  { number: 52, slug: "at-tur", nom_phonetique: "At-Tur", nom_arabe: "سورة الطور", englishNameTranslation: "The Mount" },
  { number: 53, slug: "an-najm", nom_phonetique: "An-Najm", nom_arabe: "سورة النجم", englishNameTranslation: "The Star" },
  { number: 54, slug: "al-qamar", nom_phonetique: "Al-Qamar", nom_arabe: "سورة القمر", englishNameTranslation: "The Moon" },
  { number: 55, slug: "ar-rahman", nom_phonetique: "Ar-Rahman", nom_arabe: "سورة الرحمن", englishNameTranslation: "The Beneficent" },
  { number: 56, slug: "al-waqi'a", nom_phonetique: "Al-Waqi'a", nom_arabe: "سورة الواقعة", englishNameTranslation: "The Inevitable" },
  { number: 57, slug: "al-hadid", nom_phonetique: "Al-Hadid", nom_arabe: "سورة الحديد", englishNameTranslation: "The Iron" },
  { number: 58, slug: "al-mujadila", nom_phonetique: "Al-Mujadila", nom_arabe: "سورة المجادلة", englishNameTranslation: "The Pleading Woman" },
  { number: 59, slug: "al-hashr", nom_phonetique: "Al-Hashr", nom_arabe: "سورة الحشر", englishNameTranslation: "The Exile" },
  { number: 60, slug: "al-mumtahina", nom_phonetique: "Al-Mumtahina", nom_arabe: "سورة الممتحنة", englishNameTranslation: "She that is to be examined" },
  { number: 61, slug: "as-saff", nom_phonetique: "As-Saff", nom_arabe: "سورة الصف", englishNameTranslation: "The Ranks" },
  { number: 62, slug: "al-jumu'a", nom_phonetique: "Al-Jumu'a", nom_arabe: "سورة الجمعة", englishNameTranslation: "The Congregation" },
  { number: 63, slug: "al-munafiqun", nom_phonetique: "Al-Munafiqun", nom_arabe: "سورة المنافقون", englishNameTranslation: "The Hypocrites" },
  { number: 64, slug: "at-taghabun", nom_phonetique: "At-Taghabun", nom_arabe: "سورة التغابن", englishNameTranslation: "The Mutual Disillusion" },
  { number: 65, slug: "at-talaq", nom_phonetique: "At-Talaq", nom_arabe: "سورة الطلاق", englishNameTranslation: "The Divorce" },
  { number: 66, slug: "at-tahrim", nom_phonetique: "At-Tahrim", nom_arabe: "سورة التحريم", englishNameTranslation: "The Prohibition" },
  { number: 67, slug: "al-mulk", nom_phonetique: "Al-Mulk", nom_arabe: "سورة الملك", englishNameTranslation: "The Sovereignty" },
  { number: 68, slug: "al-qalam", nom_phonetique: "Al-Qalam", nom_arabe: "سورة القلم", englishNameTranslation: "The Pen" },
  { number: 69, slug: "al-haaqqa", nom_phonetique: "Al-Haaqqa", nom_arabe: "سورة الحاقة", englishNameTranslation: "The Reality" },
  { number: 70, slug: "al-ma'arij", nom_phonetique: "Al-Ma'arij", nom_arabe: "سورة المعارج", englishNameTranslation: "The Ascending Stairways" },
  { number: 71, slug: "nuh", nom_phonetique: "Nuh", nom_arabe: "سورة نوح", englishNameTranslation: "Noah" },
  { number: 72, slug: "al-jinn", nom_phonetique: "Al-Jinn", nom_arabe: "سورة الجن", englishNameTranslation: "The Jinn" },
  { number: 73, slug: "al-muzzammil", nom_phonetique: "Al-Muzzammil", nom_arabe: "سورة المزمل", englishNameTranslation: "The Enshrouded One" },
  { number: 74, slug: "al-muddathir", nom_phonetique: "Al-Muddathir", nom_arabe: "سورة المدثر", englishNameTranslation: "The Cloaked One" },
  { number: 75, slug: "al-qiyama", nom_phonetique: "Al-Qiyama", nom_arabe: "سورة القيامة", englishNameTranslation: "The Resurrection" },
  { number: 76, slug: "al-insan", nom_phonetique: "Al-Insan", nom_arabe: "سورة الإنسان", englishNameTranslation: "Man" },
  { number: 77, slug: "al-mursalat", nom_phonetique: "Al-Mursalat", nom_arabe: "سورة المرسلات", englishNameTranslation: "The Emissaries" },
  { number: 78, slug: "an-naba", nom_phonetique: "An-Naba", nom_arabe: "سورة النبأ", englishNameTranslation: "The Tidings" },
  { number: 79, slug: "an-nazi'at", nom_phonetique: "An-Nazi'at", nom_arabe: "سورة النازعات", englishNameTranslation: "Those who drag forth" },
  { number: 80, slug: "abasa", nom_phonetique: "Abasa", nom_arabe: "سورة عبس", englishNameTranslation: "He frowned" },
  { number: 81, slug: "at-takwir", nom_phonetique: "At-Takwir", nom_arabe: "سورة التكوير", englishNameTranslation: "The Overthrowing" },
  { number: 82, slug: "al-infitar", nom_phonetique: "Al-Infitar", nom_arabe: "سورة الإنفطار", englishNameTranslation: "The Cleaving" },
  { number: 83, slug: "al-mutaffifin", nom_phonetique: "Al-Mutaffifin", nom_arabe: "سورة المطففين", englishNameTranslation: "Defrauding" },
  { number: 84, slug: "al-inshiqaq", nom_phonetique: "Al-Inshiqaq", nom_arabe: "سورة الإنشقاق", englishNameTranslation: "The Splitting Open" },
  { number: 85, slug: "al-buruj", nom_phonetique: "Al-Buruj", nom_arabe: "سورة البروج", englishNameTranslation: "The Mansions of the Stars" },
  { number: 86, slug: "at-tariq", nom_phonetique: "At-Tariq", nom_arabe: "سورة الطارق", englishNameTranslation: "The Morning Star" },
  { number: 87, slug: "al-ala", nom_phonetique: "Al-Ala", nom_arabe: "سورة الأعلى", englishNameTranslation: "The Most High" },
  { number: 88, slug: "al-ghashiya", nom_phonetique: "Al-Ghashiya", nom_arabe: "سورة الغاشية", englishNameTranslation: "The Overwhelming" },
  { number: 89, slug: "al-fajr", nom_phonetique: "Al-Fajr", nom_arabe: "سورة الفجر", englishNameTranslation: "The Dawn" },
  { number: 90, slug: "al-balad", nom_phonetique: "Al-Balad", nom_arabe: "سورة البلد", englishNameTranslation: "The City" },
  { number: 91, slug: "ash-shams", nom_phonetique: "Ash-Shams", nom_arabe: "سورة الشمس", englishNameTranslation: "The Sun" },
  { number: 92, slug: "al-lail", nom_phonetique: "Al-Lail", nom_arabe: "سورة الليل", englishNameTranslation: "The Night" },
  { number: 93, slug: "ad-duha", nom_phonetique: "Ad-Duha", nom_arabe: "سورة الضحى", englishNameTranslation: "The Morning Brightness" },
  { number: 94, slug: "ash-sharh", nom_phonetique: "Ash-Sharh", nom_arabe: "سورة الشرح", englishNameTranslation: "The Relief" },
  { number: 95, slug: "at-tin", nom_phonetique: "At-Tin", nom_arabe: "سورة التين", englishNameTranslation: "The Fig" },
  { number: 96, slug: "al-alaq", nom_phonetique: "Al-Alaq", nom_arabe: "سورة العلق", englishNameTranslation: "The Clot" },
  { number: 97, slug: "al-qadr", nom_phonetique: "Al-Qadr", nom_arabe: "سورة القدر", englishNameTranslation: "The Power" },
  { number: 98, slug: "al-bayyina", nom_phonetique: "Al-Bayyina", nom_arabe: "سورة البينة", englishNameTranslation: "The Clear Proof" },
  { number: 99, slug: "az-zalzalah", nom_phonetique: "Az-Zalzalah", nom_arabe: "سورة الزلزلة", englishNameTranslation: "The Earthquake" },
  { number: 100, slug: "al-adiyat", nom_phonetique: "Al-Adiyat", nom_arabe: "سورة العاديات", englishNameTranslation: "The Chargers" },
  { number: 101, slug: "al-qari'a", nom_phonetique: "Al-Qari'a", nom_arabe: "سورة القارعة", englishNameTranslation: "The Calamity" },
  { number: 102, slug: "at-takathur", nom_phonetique: "At-Takathur", nom_arabe: "سورة التكاثر", englishNameTranslation: "The Rivalry in world increase" },
  { number: 103, slug: "al-asr", nom_phonetique: "Al-Asr", nom_arabe: "سورة العصر", englishNameTranslation: "The Declining Day" },
  { number: 104, slug: "al-humazah", nom_phonetique: "Al-Humazah", nom_arabe: "سورة الهمزة", englishNameTranslation: "The Traducer" },
  { number: 105, slug: "al-fil", nom_phonetique: "Al-Fil", nom_arabe: "سورة الفيل", englishNameTranslation: "The Elephant" },
  { number: 106, slug: "quraish", nom_phonetique: "Quraish", nom_arabe: "سورة قريش", englishNameTranslation: "Quraysh" },
  { number: 107, slug: "al-ma'un", nom_phonetique: "Al-Ma'un", nom_arabe: "سورة الماعون", englishNameTranslation: "The Small Kindnesses" },
  { number: 108, slug: "al-kawthar", nom_phonetique: "Al-Kawthar", nom_arabe: "سورة الكوثر", englishNameTranslation: "The Abundance" },
  { number: 109, slug: "al-kafiroon", nom_phonetique: "Al-Kafiroon", nom_arabe: "سورة الكافرون", englishNameTranslation: "The Disbelievers" },
  { number: 110, slug: "an-nasr", nom_phonetique: "An-Nasr", nom_arabe: "سورة النصر", englishNameTranslation: "The Divine Support" },
  { number: 111, slug: "al-masad", nom_phonetique: "Al-Masad", nom_arabe: "سورة المسد", englishNameTranslation: "The Palm Fiber" },
  { number: 112, slug: "al-ikhlas", nom_phonetique: "Al-Ikhlas", nom_arabe: "سورة الإخلاص", englishNameTranslation: "The Sincerity" },
  { number: 113, slug: "al-falaq", nom_phonetique: "Al-Falaq", nom_arabe: "سورة الفلق", englishNameTranslation: "The Daybreak" },
  { number: 114, slug: "an-nas", nom_phonetique: "An-Nas", nom_arabe: "سورة الناس", englishNameTranslation: "Mankind" },
];
